@startuml
title: <size:20>TMOS Whiffie <&double-quote-serif-left>Chatbot<&double-quote-serif-right> Flow</size>

start

:Q & A;
:Items Recommended by our Messenger;
if (Accept and Select From the recommended items?) then (yes)

    if (Member?) then (yes)
        :Process Order;
        :Dashboard;
    else (no)
        if (Agree to Sign-up?) then (yes)
            :Process Sign up;
        else (no)
            :Look around;
        endif

    endif

else (no)
    :Look around;
endif

stop
@enduml