@startuml
!theme sketchy-outline

title <size:20> <&chevron-right> TMOS Use Case Diagram

left to right direction
actor Guest as g
actor Member as m


package Whiffie {
  usecase "Chat Bot" as UC1
  usecase "Word / Memory Game" as UC2

}

package Wiki {
  usecase "Search" as UC3
  usecase "Rate & Review" as UC4
}

package Selfie {
  usecase "Profile" as UC5
  usecase "Dashboard" as UC6
  usecase "Portfolio" as UC7
}

UC1 <-- g : Play
UC2 <-- g : Play
UC3 "Use" <-- g
UC4 <-.- g : "View"
'UC7 <-- UC4


m --> UC1 : Play and Gain
m <--> UC2 : Play and Gain
m ----> "Use" UC3
m <-----> UC4 : Contribute and Gain
m ----> UC5 : "Update"
m ----> UC6 : "View"
m ----> UC7 :  "Build"


@enduml