@startuml
title <size:20> TMOS <&excerpt> Wiki Flow

start

repeat
  :Search Catalog;
  :View List of Results;

repeat while (Not done with selection?)

:View Item Details;
:Rate or Comment?;

if (Is Member?) then (yes)
  :Rate Item;
  :Leave Comment;
else (no)
  :Prompt Sign-up;
endif

stop
@enduml
