@startuml
title TMOS Whiffie Chatbot Flow
start

:Q & A;
:Recommended bottle by our Messenger;
if (Accept the recommendation?) then (yes)

    if (Member?) then (yes)
        :Process Order;
        :Dashboard;
    else (no)
        if (Agree to Sign-up?) then (yes)
            :Process Sign up;
        else (no)
            :Look around;
        endif

    endif

else (no)
    :Look around;
endif

stop
@enduml