@startuml
!theme sketchy
skinparam handwritten true
skinparam packageBorderColor white

skinparam usecase {
  BackgroundColor #FAFAFA
  FontColor #212121
  BorderColor #BDBDBD
  FontSize 13
}
skinparam ArrowFontColor black
skinparam ActorFontColor black


title <size:20> <&chevron-right> TMOS Use Case Diagram

left to right direction
actor Guest as g
actor Member as m


package Whiffie #FFEB3B {
  usecase "Chat Bot" as UC1
  usecase "Word / Memory Game" as UC2

}

package Wiki #FFEB3B {
  usecase "Search" as UC3
  usecase "Rate & Review" as UC4
}

package Selfie #FFEB3B {
  usecase "Profile" as UC5
  usecase "Dashboard" as UC6
  usecase "Portfolio" as UC7
}

UC1 <-- g : Play
UC2 <-- g : Play
UC3 <-- g : Use
UC4 <-.- g : View
'UC7 <-- UC4


m <-[#orange]-> UC1 : Play and Gain
m <-[#red]-> UC2 : Play and Gain
m ----> UC3 : Use
m <--[#red]---> UC4 : Contribute and Gain
m ----> UC5 : Update
m ----> UC6 : View
m ----> UC7 : Build



@enduml