@startuml
skinparam nodesep 40

left to right direction
actor Guest as g
actor Member as m


package Whiffie {
  usecase "Chat Bot" as UC1
  usecase "Word / Memory Game" as UC2

}

package Wiki {
  usecase "Search" as UC3
  usecase "Review" as UC4
}

package Selfie {
  usecase "My Profile" as UC5
  usecase "My Dashboard" as UC6
  usecase "My Collection" as UC7

}

UC1 <-- g
UC2 <-- g
UC3 <-- g
m --> UC1

m ----> UC2
m ----> UC3
m ----> UC4
m -----> UC5
m -----> UC6
m -----> UC7
@enduml